version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'myuser'
      MYSQL_PASSWORD: 'mypassword'
      MYSQL_ROOT_PASSWORD: 'myrootpassword'
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 'myrootpassword'
    ports:
      - '8080:80'
    depends_on:
      - db


